version: 2.1

orbs:
  node: circleci/node@4.7
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Lint
          command: yarn lint:report || true
      - run:
          name: Test
          command: yarn test:ci
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build-and-test:
          context: SonarCloud
